settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 50001
  host: localhost
schema:
  - name: medilink
    path: cmd/api/
    commands: 
      install:
        status: true
      run:
        status: true
    watcher:
      extensions:
        - go
        - yaml
        - json
      paths:
        - ../../
      ignore:
        paths:
          - .git
          - .realize
          - vendor
