version: '3.8'

services:
  psql:
    image: timescale/timescaledb:latest-pg15
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
