#!/usr/bin/env python3
"""
Convert docs/ICD9 CM.csv into INSERT statements for mdl_ref_icd9cm.

Hierarchy derivation from dotted ICD-9-CM codes:
  depth 0: chapter codes with no dot, e.g. "00", "01" ... "99"
  depth 1: one-decimal codes, e.g. "00.0", "00.1"
  depth 2: two-decimal codes, e.g. "00.01", "00.09"  (most are leaves)

parent_code: strip last character after last dot; if no dot, parent = NULL.

Usage:
  python3 scripts/icd9cm_csv_to_sql.py \
      --input "docs/ICD9 CM.csv" \
      --output schema/medianne/20260706_seed_ref_icd9cm.sql \
      [--batch-size 500]
"""

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Row:
    code: str
    display: str
    parent_code: str | None
    depth: int
    is_leaf: bool
    version: str


def parent_of(code: str) -> str | None:
    """Derive parent code by trimming the last dotted segment."""
    if "." not in code:
        return None
    left, right = code.split(".", 1)
    if len(right) > 1:
        return f"{left}.{right[:-1]}"
    return left


def depth_of(code: str) -> int:
    if "." not in code:
        return 0
    return len(code.split(".", 1)[1])


def load_csv(path: Path) -> list[Row]:
    with path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        raw = [(r["CODE"].strip(), r["DISPLAY"].strip(), r.get("VERSION", "ICD9CM_2010").strip()) for r in reader]

    codes: set[str] = {code for code, _, _ in raw}
    rows: list[Row] = []
    for code, display, version in raw:
        parent = parent_of(code)
        depth = depth_of(code)
        # a code is a leaf if nothing in the dataset uses it as a parent
        children_exist = any(parent_of(c) == code for c in codes)
        rows.append(Row(
            code=code,
            display=display,
            parent_code=parent,
            depth=depth,
            is_leaf=not children_exist,
            version=version,
        ))
    return rows


def escape(s: str) -> str:
    return s.replace("'", "''")


def emit_sql(rows: list[Row], out: Path, batch_size: int) -> None:
    lines = [
        "-- ICD-9-CM seed data generated by scripts/icd9cm_csv_to_sql.py",
        "-- Source: docs/ICD9 CM.csv (ICD9CM_2010)",
        f"-- Total rows: {len(rows)}",
        "",
        "INSERT INTO mdl_ref_icd9cm (code, display, parent_code, depth, is_leaf, version) VALUES",
    ]

    value_lines: list[str] = []
    for row in rows:
        parent_sql = f"'{escape(row.parent_code)}'" if row.parent_code else "NULL"
        is_leaf_sql = "TRUE" if row.is_leaf else "FALSE"
        value_lines.append(
            f"  ('{escape(row.code)}', '{escape(row.display)}', {parent_sql}, {row.depth}, {is_leaf_sql}, '{escape(row.version)}')"
        )

    # Emit in batches (split into multiple INSERT statements)
    for i in range(0, len(value_lines), batch_size):
        chunk = value_lines[i : i + batch_size]
        if i == 0:
            lines.append(",\n".join(chunk) + ";")
        else:
            lines.append("")
            lines.append("INSERT INTO mdl_ref_icd9cm (code, display, parent_code, depth, is_leaf, version) VALUES")
            lines.append(",\n".join(chunk) + ";")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {out}", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", default="docs/ICD9 CM.csv", help="Path to ICD9 CM.csv")
    parser.add_argument("--output", default="schema/medianne/20260706_seed_ref_icd9cm.sql", help="Output SQL file")
    parser.add_argument("--batch-size", type=int, default=500, help="Rows per INSERT statement")
    args = parser.parse_args()

    rows = load_csv(Path(args.input))
    emit_sql(rows, Path(args.output), args.batch_size)


if __name__ == "__main__":
    main()
